# This file was generated by GoReleaser. DO NOT EDIT.
class DiCli < Formula
  desc ""
  homepage ""
  version "0.0.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jasonblanchard/di-cli/releases/download/v0.0.12/di-cli_0.0.12_Darwin_x86_64.tar.gz"
    sha256 "514c57146d6730d751be31b77a0c20788b13c120aadb4f06974a7bcca990c779"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jasonblanchard/di-cli/releases/download/v0.0.12/di-cli_0.0.12_Linux_x86_64.tar.gz"
    sha256 "d358d20441a6011b3f6e4ab4b5fd0c3beeba2f35e7b3e6d1b525d6989cefcc13"
  end

  def install
    system "cp", "di-cli", "di"
    bin.install "di"
  end
end
