# This file was generated by GoReleaser. DO NOT EDIT.
class Di < Formula
  desc ""
  homepage ""
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jasonblanchard/di-cli/releases/download/v0.0.8/di-cli_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "763d184200ac5e894081af724401a7b43beac96383cb03c7baf48000b57437ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jasonblanchard/di-cli/releases/download/v0.0.8/di-cli_0.0.8_Linux_x86_64.tar.gz"
      sha256 "a46500ad9008cb3c354d8e2c4dc44eb28ae77c15b5509cfc59a2c1ad62832dc2"
    end
  end

  def install
    bin.install "di"
  end
end
