# This file was generated by GoReleaser. DO NOT EDIT.
class Di < Formula
  desc ""
  homepage ""
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/foo/bar/releases/v0.0.6/di-cli_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "e1e967e088f009f3962ef66fbe3fb22656f8370e67ab81596d87f50abb6e0c62"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.mycompany.com/foo/bar/releases/v0.0.6/di-cli_0.0.6_Linux_x86_64.tar.gz"
      sha256 "23fa973278dc1d903754b5bfa619269986feb253e3017f1459d41519da251679"
    end
  end

  def install
    bin.install "di-cli"
  end
end
